version: "3.8"
services:
  jenkins:
    build:
      context: ./dockerfiles
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home

