version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:2.249.3-lts-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home

