name: CI Docker Images

on:
  push:
    branches: [ main ]

jobs:
  jenkins:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build custom jenkins image
        run: docker build -t mikadows/jenkins:latest -f dockerfiles/jenkins.Dockerfile ./dockerfiles/
      -
        name: Push previous image on DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push mikadows/jenkins:latest